// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using voto;

#nullable disable

namespace voto.API.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20260131011752_CargoCandidato")]
    partial class CargoCandidato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoVotoElectronico.Candidato", b =>
                {
                    b.Property<int>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCandidato"));

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<int?>("EleccionIdEleccion")
                        .HasColumnType("integer");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("IdEleccion")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLista")
                        .HasColumnType("integer");

                    b.Property<int?>("ListaPoliticaIdlista")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Propuesta")
                        .HasColumnType("text");

                    b.HasKey("IdCandidato");

                    b.HasIndex("EleccionIdEleccion");

                    b.HasIndex("ListaPoliticaIdlista");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Eleccion", b =>
                {
                    b.Property<int>("IdEleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEleccion"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("IdEleccion");

                    b.ToTable("Elecciones");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.ListaPolitica", b =>
                {
                    b.Property<int>("Idlista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idlista"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreLista")
                        .HasColumnType("text");

                    b.Property<string>("UrlLogo")
                        .HasColumnType("text");

                    b.HasKey("Idlista");

                    b.HasIndex("EleccionId");

                    b.ToTable("ListasPoliticas");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.RegistroVotacion", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdEleccion")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdEleccion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RegistroVotaciones");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResultado"));

                    b.Property<int?>("EleccionIdEleccion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdEleccion")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoAsignacion")
                        .HasColumnType("text");

                    b.Property<int>("TotalVotos")
                        .HasColumnType("integer");

                    b.HasKey("IdResultado");

                    b.HasIndex("EleccionIdEleccion");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Voto", b =>
                {
                    b.Property<int>("IdVoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVoto"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashVoto")
                        .HasColumnType("text");

                    b.Property<int?>("IdCandidato")
                        .HasColumnType("integer");

                    b.Property<int>("IdEleccion")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLista")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdVoto");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("IdEleccion");

                    b.HasIndex("IdLista");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Candidato", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany("Candidatos")
                        .HasForeignKey("EleccionIdEleccion");

                    b.HasOne("ProyectoVotoElectronico.ListaPolitica", "ListaPolitica")
                        .WithMany("Candidatos")
                        .HasForeignKey("ListaPoliticaIdlista");

                    b.Navigation("Eleccion");

                    b.Navigation("ListaPolitica");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.ListaPolitica", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.RegistroVotacion", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("IdEleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoVotoElectronico.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Resultado", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionIdEleccion");

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Usuario", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Voto", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("IdCandidato");

                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("IdEleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoVotoElectronico.ListaPolitica", "Lista")
                        .WithMany()
                        .HasForeignKey("IdLista");

                    b.Navigation("Candidato");

                    b.Navigation("Eleccion");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Eleccion", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.ListaPolitica", b =>
                {
                    b.Navigation("Candidatos");
                });
#pragma warning restore 612, 618
        }
    }
}
