// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using voto;

#nullable disable

namespace voto.API.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoVotoElectronico.Candidato", b =>
                {
                    b.Property<int>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCandidato"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EleccionIdEleccion")
                        .HasColumnType("integer");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdEleccion")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Propuesta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCandidato");

                    b.HasIndex("EleccionIdEleccion");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Eleccion", b =>
                {
                    b.Property<int>("IdEleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEleccion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEleccion");

                    b.ToTable("Elecciones");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.ListaPolitica", b =>
                {
                    b.Property<int>("Idlista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idlista"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Idlista");

                    b.HasIndex("EleccionId");

                    b.ToTable("ListasPoliticas");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResultado"));

                    b.Property<int>("EleccionIdEleccion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEleccion")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoAsignacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalVotos")
                        .HasColumnType("integer");

                    b.HasKey("IdResultado");

                    b.HasIndex("EleccionIdEleccion");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo2FA")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CodigoExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Voto", b =>
                {
                    b.Property<int>("IdVoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVoto"));

                    b.Property<int>("CandidatoIdCandidato")
                        .HasColumnType("integer");

                    b.Property<int>("EleccionIdEleccion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashVoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCandidato")
                        .HasColumnType("integer");

                    b.Property<int>("IdEleccion")
                        .HasColumnType("integer");

                    b.HasKey("IdVoto");

                    b.HasIndex("CandidatoIdCandidato");

                    b.HasIndex("EleccionIdEleccion");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Candidato", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany("Candidatos")
                        .HasForeignKey("EleccionIdEleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.ListaPolitica", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Resultado", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionIdEleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Usuario", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Voto", b =>
                {
                    b.HasOne("ProyectoVotoElectronico.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoIdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoVotoElectronico.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("EleccionIdEleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("ProyectoVotoElectronico.Eleccion", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
